import Head from "next/head";
import QrCode from "@/components/QrCode";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>QR Code Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col items-center justify-center bg-slate-100">
        <QrCode />
        <Footer />
      </div>
    </>
  );
}
